language: node_js
node_js:
  - "10"

cache:
  yarn: true

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: false
  name: moyangzhen
  email: 15711476734@163.com
  on:
    branch: main
